# Generated by Django 5.0.7 on 2024-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='static/')),
                ('compostos', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('feito', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Resultados',
            },
        ),
    ]
