# Generated by Django 5.0.7 on 2024-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='feito',
            field=models.TextField(verbose_name='Do que é composto'),
        ),
    ]
