# Generated by Django 5.0.7 on 2024-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_resultado_feito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='feito',
            field=models.TextField(),
        ),
    ]
