# Generated by Django 5.0.7 on 2024-07-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_resultado_feito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='compostos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='origem',
            field=models.TextField(),
        ),
    ]
