# Generated by Django 5.0.7 on 2024-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='link',
            field=models.TextField(null=True, verbose_name='link do composto em 3D'),
        ),
    ]
